version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    groups:
      frontend-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
      day: monday
    groups:
      backend-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
